#################################################################
#                                                               #
#                      Packages/Cameras                         #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
          
    ## שינוי שמות לאוטומציה של כיבוי המצלמה ##
    automation.turn_on_xiaomi_cameras_if_nurit_and_avi_not_at_home:
      friendly_name: פעיל - אני ונורית לא בבית
      icon: mdi:cctv
      home_assistant: true
      
    automation.turn_off_xiaomi_cameras_if_avi_at_home:
      friendly_name: כיבוי מצלמה - אבי בבית
      icon: mdi:cctv
      home_assistant: true
      
    automation.turn_off_xiaomi_cameras_if_nurit_at_home:
      friendly_name: כיבוי מצלמה - נורית בבית
      icon: mdi:cctv
      home_assistant: true

    automation.turn_on_cctv_cameras_if_late_night:
      friendly_name: פעיל - מצלמה פעילה 23:00
      icon: mdi:cctv
      home_assistant: true

    automation.turn_off_xiaomi_cameras_if_morning_and_we_are_at_home:
      friendly_name: כיבוי מצלמה 7 בבוקר
      icon: mdi:cctv
      home_assistant: true

    automation.avi_wifi_off:
      friendly_name: הפעלת מצלמת שיאומי - וויפי אבי מכובה
      icon: mdi:wifi-off
      home-assistant: true

    automation.avi_wifi_on:
      friendly_name: כיבוי מצלמת שיאומי - וויפי אבי פעיל
      icon: mdi:wifi
      home-assistant: true  

    automation.nurit_wifi_off:
      friendly_name: הפעלת מצלמת שיאומי - וויפי נורית מכובה
      icon: mdi:wifi-off
      home-assistant: true  

    automation.nurit_wifi_on:
      friendly_name: כיבוי מצלמת שיאומי - וויפי נורית פעיל
      home-assistant: true

    automation.yakir_wifi_off:    
      friendly_name: זיהוי מצב ה וויפי של יקיר - לא זמין
      icon: mdi:wifi-off
      home-assistant: true

    automation.yakir_wifi_on:
      friendly_name: זיהוי מצב ה וויפי של יקיר - זמין
      icon: mdi:wifi
      home-assistant: true


#################################################################
#                                                               #
#                          cameras                              #
#                                                               #
#################################################################
camera:

  ## hikvision Camera 3mp ## 
    - platform: ffmpeg
      input: !secret camera_3mp_entrance_to_the_building
      name: Entrance To The Building

  ## Front Door Camera ##
    - platform: ffmpeg
      input: !secret front_door_camera_ip_url
      name: Front Door Camera

  ## Dahua Camera ##
    - platform: onvif
      name: Dahua Camera 
      host: !secret dahua_host
      profile: 0 # 0 for SuperHD
      port: 80
      username: !secret dahua_username
      password: !secret dahua_password  

      
  ## Dahua Camera 6mp ##
    - platform: ffmpeg
      input: !secret dahua_6m
      name: Dahua Camera 6m

              
#################################################################
#                                                               #
#                           Groups                              #
#                                                               #
#################################################################
group:
  Outside the home:
    name: Outside Camera
    view: no
    entities:
      - camera.entrance_to_the_building
      - camera.dahua_camera
      - camera.dahua_camera_6m

  inside the home:
    name: Home Fornt Dor Camera 
    view: no
    entities:
      - camera.front_door_camera
    
      

    
#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################
automation:
  - alias: frontdoor_snapshot
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: 'binary_sensor.door_window_sensor_158d0001ef3425'
      to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'device_tracker.avi_note8'
          state: 'not_home'
        - condition: state
          entity_id: 'device_tracker.iphone_nurit'
          state: 'not_home'
    action:
      - service: camera.snapshot
        data:
          entity_id: camera.front_door_camera
          filename: "/config/tmp/front_house_{{ now().year }}_{{ now().month }}_{{ now().day }}_{{ now().hour }}_{{ now().minute }}.jpg"
      # - delay: 
      #   seconds: 5
      - service: notify.AviTelegram
        data:
          message: "הדלת נפתחה"
          data:
            photo:
              - file: "/config/tmp/front_house_{{ now().year }}_{{ now().month }}_{{ now().day }}_{{ now().hour }}_{{ now().minute }}.jpg"
                capture: Front House Camera              