#################################################################
#                                                               #
#                   Packages/Things Status                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:

  
#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################
group:
  cameras:
    name: Cameras
    view: no
    entities:
      - binary_sensor.front_door_camera
      - binary_sensor.dahua_camera
      - binary_sensor.front_camera_building
      - binary_sensor.high_quality_camera

      
  smart_home:
    name: Smart Home
    view: no
    entities:
      - binary_sensor.broadlink
      - binary_sensor.amzonecho
      
  wall_switches:
    name: Wall Switches
    view: no
    entities:
      - binary_sensor.light_switch_poop
      - binary_sensor.wall_switch_prozdor
      - binary_sensor.wall_switch_laundry
      - binary_sensor.wall_switch_miklahat
      - binary_sensor.sonoff_tris    
      
  light_bulbs:
    name: Light Bulbs
    view: no
    entities:
      - binary_sensor.light_balcony_sonoff
      - binary_sensor.sonoff_light_liran
      - binary_sensor.sonoff_service_balcony_light
      - binary_sensor.sonoff_stairs_light
      - binary_sensor.sonoff_parents_light
      - binary_sensor.yeelinklightcolor1_miio86767262
      
  fan:
    name: Fan Sonoff
    view: no
    entities:
      - binary_sensor.sonff_fan
      
  network_connection:
    name: Network connections
    view: no
    entities:
      - binary_sensor.unifi_access_point

#################################################################
#                                                               #
#                          Sensors                              #
#                                                               #
################################################################# 
sensor:
       
       

#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:
  - platform: template
    sensors:
      front_door_camera:
        friendly_name: Front Door Camera
        device_class: connectivity
        entity_id: device_tracker.front_door_camera
        value_template: "{{ is_state('device_tracker.front_door_camera', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.front_door_camera', 'home') %}
            mdi:cctv
          {% else %}
            mdi:alert
          {% endif %}

## dahua_camera
      dahua_camera:
        friendly_name: Dahua Camera (3M)
        device_class: connectivity
        entity_id: device_tracker.dahua_camera
        value_template: "{{ is_state('device_tracker.dahua_camera', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.dahua_camera', 'home') %}
            mdi:cctv
          {% else %}
            mdi:alert
          {% endif %}

## front camera building
      front_camera_building:
        friendly_name: Building Camera
        device_class: connectivity
        entity_id: device_tracker.front_camera_building
        value_template: "{{ is_state('device_tracker.front_camera_building', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.front_camera_building', 'home') %}
            mdi:cctv
          {% else %}
            mdi:alert
          {% endif %}

## bedroom_camera
      bedroom_camera:
        friendly_name: Bedroom Camera
        device_class: connectivity
        entity_id: device_tracker.bedroom_camera
        value_template: "{{ is_state('device_tracker.bedroom_camera', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.bedroom_camera', 'home') %}
            mdi:cctv
          {% else %}
            mdi:alert
          {% endif %}

## high quality camera
      high_quality_camera:
        friendly_name: High Quality Camera
        device_class: connectivity
        entity_id: device_tracker.high_quality_camera
        value_template: "{{ is_state('device_tracker.high_quality_camera', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.high_quality_camera', 'home') %}
            mdi:cctv
          {% else %}
            mdi:alert
          {% endif %}          

      
## Smart home
      broadlink:
        friendly_name: Broadlink
        device_class: connectivity
        entity_id: device_tracker.broadlink
        value_template: "{{ is_state('device_tracker.broadlink', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.broadlink', 'home') %}
            mdi:remote
          {% else %}
            mdi:alert
          {% endif %}

## amzonecho
      amzonecho:
        friendly_name: Amzon Echo
        device_class: connectivity
        entity_id: device_tracker.amzonecho
        value_template: "{{ is_state('device_tracker.amzonecho', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.amzonecho', 'home') %}
            mdi:remote
          {% else %}
            mdi:alert
          {% endif %}         

## wall Sonoff Swiches
      light_switch_poop:
        friendly_name: Light Switch Poop
        device_class: connectivity
        entity_id: device_tracker.light_switch_poop
        value_template: "{{ is_state('device_tracker.light_switch_poop', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.light_switch_poop', 'home') %}
            mdi:toggle-switch
          {% else %}
            mdi:alert
          {% endif %}
 
## wall switch prozdor
      wall_switch_prozdor:
        friendly_name: Light Switch Prozdor
        device_class: connectivity
        entity_id: device_tracker.wall_switch_prozdor
        value_template: "{{ is_state('device_tracker.wall_switch_prozdor', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.wall_switch_prozdor', 'home') %}
            mdi:toggle-switch
          {% else %}
            mdi:alert
          {% endif %}
 
## wall switch laundry 
      wall_switch_laundry:
        friendly_name: Wall Switch Laundry
        device_class: connectivity
        entity_id: device_tracker.wall_switch_laundry
        value_template: "{{ is_state('device_tracker.wall_switch_laundry', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.wall_switch_laundry', 'home') %}
            mdi:toggle-switch
          {% else %}
            mdi:alert
          {% endif %}

## wall switch miklahat
      wall_switch_miklahat:
        friendly_name: Wall Switch Miklahat
        device_class: connectivity
        entity_id: device_tracker.wall_switch_miklahat
        value_template: "{{ is_state('device_tracker.wall_switch_miklahat', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.wall_switch_miklahat', 'home') %}
            mdi:toggle-switch
          {% else %}
            mdi:alert
          {% endif %}

## sonoff tris
      sonoff_tris:
        friendly_name: Wall Switch Tris (sonoff)
        device_class: connectivity
        entity_id: device_tracker.sonoff_tris
        value_template: "{{ is_state('device_tracker.sonoff_tris', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.sonoff_tris', 'home') %}
            mdi:toggle-switch
          {% else %}
            mdi:alert
          {% endif %}          


## Light Bulbs
      light_balcony_sonoff:
        friendly_name: Sonoff Light Balcony
        device_class: connectivity
        entity_id: device_tracker.light_balcony_sonoff
        value_template: "{{ is_state('device_tracker.light_balcony_sonoff', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.light_balcony_sonoff', 'home') %}
            mdi:lightbulb
          {% else %}
            mdi:alert
          {% endif %}

## sonoff light liran
      sonoff_light_liran:
        friendly_name: Liran Sonoff Light
        device_class: connectivity
        entity_id: device_tracker.sonoff_light_liran
        value_template: "{{ is_state('device_tracker.sonoff_light_liran', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.sonoff_light_liran', 'home') %}
            mdi:lightbulb
          {% else %}
            mdi:alert
          {% endif %}
## sonoff service balcony light
      sonoff_service_balcony_light:
        friendly_name: Light Service Balcony (Sonoff)
        device_class: connectivity
        entity_id: device_tracker.sonoff_service_balcony_light
        value_template: "{{ is_state('device_tracker.sonoff_service_balcony_light', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.sonoff_service_balcony_light', 'home') %}
            mdi:lightbulb
          {% else %}
            mdi:alert
          {% endif %}

## sonoff stairs light
      sonoff_stairs_light:
        friendly_name: Stairs Sonoff Light
        device_class: connectivity
        entity_id: device_tracker.sonoff_stairs_light
        value_template: "{{ is_state('device_tracker.sonoff_stairs_light', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.sonoff_stairs_light', 'home') %}
            mdi:lightbulb
          {% else %}
            mdi:alert
          {% endif %}

## sonoff parents light 
      sonoff_parents_light:
        friendly_name: Parents Sonoff
        device_class: connectivity
        entity_id: device_tracker.sonoff_parents_light
        value_template: "{{ is_state('device_tracker.sonoff_parents_light', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.sonoff_parents_light', 'home') %}
            mdi:lightbulb
          {% else %}
            mdi:alert
          {% endif %}

## yeelink light color
      yeelinklightcolor1_miio86767262:
        friendly_name: Yeelink Light Color
        device_class: connectivity
        entity_id: device_tracker.yeelinklightcolor1_miio86767262
        value_template: "{{ is_state('device_tracker.yeelinklightcolor1_miio86767262', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.yeelinklightcolor1_miio86767262', 'home') %}
            mdi:lightbulb
          {% else %}
            mdi:alert
          {% endif %}          
          
## Network connection
      unifi_access_point:
        friendly_name: Unifi Access Point
        device_class: connectivity
        entity_id: device_tracker.unifi_access_point
        value_template: "{{ is_state('device_tracker.unifi_access_point', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.unifi_access_point', 'home') %}
            mdi:access-point-network
          {% else %}
            mdi:alert
          {% endif %}
## Electrical Power
      esp_electric:
        friendly_name: Electric ESP
        device_class: connectivity
        entity_id: device_tracker.esp_electric
        value_template: "{{ is_state('device_tracker.esp_electric', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.esp_electric', 'home') %}
            mdi:garage
          {% else %}
            mdi:alert
          {% endif %}

## blitzwolf tami4 
      blitzwolf_tami4:
        friendly_name: BlitzWolf Tami4
        device_class: connectivity
        entity_id: device_tracker.blitzwolf_tami4
        value_template: "{{ is_state('device_tracker.blitzwolf_tami4', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.blitzwolf_tami4', 'home') %}
            mdi:garage
          {% else %}
            mdi:alert
          {% endif %}

## Fan
      sonff_fan:
        friendly_name: Fan Sonff
        device_class: connectivity
        entity_id: device_tracker.sonff_fan
        value_template: "{{ is_state('device_tracker.sonff_fan', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.sonff_fan', 'home') %}
            mdi:toggle-switch
          {% else %}
            mdi:alert
          {% endif %}          



                