#################################################################
#                                                               #
#                    Packages/Xiaomi vacuum                     #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    vacuum.xiaomi_vacuum_cleaner:
      friendly_name: Xiaomi MiRo
      home-assistant: true
  
    input_boolean.disable_daily_vacuum:
      friendly_name: "Robot - abilita la soppressione automatica dell'aspirazione"
      icon: mdi:cancel
      home-assistant: true
  
    input_boolean.disable_dustbin_notification:
      friendly_name: "Robot - Disattiva le notifiche"
      icon: mdi:bell-off
      hidden: true
  
    input_boolean.daily_vacuum_first_run:
      friendly_name: "Robot - Avviare l'operazione della pompa a partire da domenica"
      icon: mdi:calendar-blank
      hidden: true 
  
    automation.start_cleaning_room:
      friendly_name: "Inizia a pulire la stanza"
      home-assistant: true
  
    automation.start_daily_vacuum:
      friendly_name: "Applicare il pompaggio ogni giorno"
      icon: mdi:robot-vacuum-variant
      home-assistant: true
  
    automation.send_alert_after_daily_vacuum_to_empty_the_dustbin:
      friendly_name: "Notificare se l'aspirapolvere è pieno"
      icon: mdi:delete-empty
      home-assistant: true
  
    automation.reset_daily_vacuum_first_run_state_at_midnight:
      friendly_name: "Invia ripristinato al vuoto dopo la mezzanotte"
      icon: mdi:lock-reset
      home-assistant: true
  
    input_select.vacuum_room:
      friendly_name: "Seleziona una zona da pulire"
      icon: mdi:broom
      hidden: true
  
    group.vacuum_a_room:
      friendly_name: "Seleziona un'area di pompaggio"
      home-assistant: true 
  
    group.robot_vacuum: 
      friendly_name: "Aspirapolvere"
      home-assistant: true
  
    script.vacuum_all_home:
      friendly_name: "Robot - pompa tutta la casa"
      icon: mdi:home-variant
      home-assistant: true
  
    script.vacuum_corridor:
      friendly_name: "Robot - pompa fuori il corridoio"
      icon: mdi:transition
      home-assistant: true
  
    script.vacuum_dining_room:
      friendly_name: "Robot - sala da pranzo"
      icon: mdi:silverware
      home-assistant: true
  
    script.vacuum_dogs_area:
      friendly_name: "Robot - pompa nell'area dei cani"
      icon: mdi:cat
      home-assistant: true
  
    script.vacuum_kitchen:
      friendly_name: "Robot - Cucina"
      icon: mdi:fridge
      home-assistant: true
  
    script.vacuum_living_room:
      friendly_name: "Robot - soggiorno"
      icon: mdi:chair-school
      home-assistant: true  


#################################################################
#                                                               #
#                          input                                #
#                                                               #
#################################################################
input_select:
  vacuum_room:
    name: Choose a room to clean
    options:
      - Select Input
      - All The House Space ## Tutta la casa ##      
      - Kitchen      ## cucina ##
      - Living Room  ## Soggiorno ##
      - Dining Room  ## Sala da pranzo ## 
      - Corridor     ## corridoio ## 
      - Dogs area    ## Area cani ##    

input_boolean:
  daily_vacuum_first_run:
    name: Daily Vacuum First Run
    initial: 'off'
  disable_daily_vacuum:
    name: Disable Daily Vacuum Automation
    initial: 'off'
  disable_dustbin_notification:
    name: Disable Dustbin Notification
    initial: 'off'
  

#################################################################
#                                                               #
#                           Groups                              #
#                                                               #
#################################################################
group: 
  home_view:
    view: yes
    icon: mdi:robot-vacuum
    entities:
      - group.robot_vacuum
      - group.vacuum_a_room

  Robot Vacuum:
    control: hidden
    entities:
      - vacuum.xiaomi_vacuum_cleaner
      - input_boolean.disable_daily_vacuum
      
  Vacuum a Room:
    control: hidden
    entities:
      - input_select.vacuum_room
      - binary_sensor.vacuum_room
  zones:
    name: home floorplan
    entities:
      - binary_sensor.floorplan

#################################################################
#                                                               #
#                           sensor                              # 
#                                                               #
#################################################################
sensor:
  - platform: template
    sensors:
      vacuum_status:
        friendly_name: Status
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: 'Status: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}'
        icon_template: >
          {% set val =  states.vacuum.xiaomi_vacuum_cleaner.attributes.status  %}
          {% if val == 'Charging' %}
            mdi:battery-charging
          {% elif val == 'Cleaning' %}
            mdi:move-resize
          {% elif val == 'Returning home' %}
            mdi:keyboard-return
          {% elif val == 'Idle' %}
            mdi:dots-horizontal
          {% elif val == 'Paused' %}
            mdi:pause-circle
          {% else %}
            mdi:help-circle
          {% endif %}
      vacuum_fan_speed:
        friendly_name: Fan Speed
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: 'Mode: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.fan_speed }}'
        icon_template: 'mdi:speedometer'
      vacuum_battery:
        friendly_name: Vacuum Battery
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: 'Battery: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level }}'
        unit_of_measurement: '%'
        icon_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_icon }}'
      vacuum_cleaning_time:
        friendly_name: Time of Last Cycle
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaning_time }}'
        icon_template: 'mdi:timer'
      vacuum_cleaned_area:
        friendly_name: Area of Last Cycle
        unit_of_measurement: 'm ²'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaned_area }}'
        icon_template: 'mdi:ruler'
      vacuum_cleanmainbrush:
        friendly_name: Replace main brush
        unit_of_measurement: 'h'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: 'Main Brush: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.main_brush_left }}'
        icon_template: 'mdi:screwdriver'
      vacuum_cleansidebrush:
        friendly_name: Replace side brush
        unit_of_measurement: 'h'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: 'Side brush: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.side_brush_left }}'
        icon_template: 'mdi:screwdriver'
      vacuum_cleanfilter:
        friendly_name: Replace filter
        unit_of_measurement: 'h'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: 'Filter: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.filter_left }}'
        icon_template: 'mdi:screwdriver'
      vacuum_sensordirtyleft:
        friendly_name: Replace filter
        unit_of_measurement: 'h'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: 'Sensor: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.sensor_dirty_left }}'
        icon_template: 'mdi:screwdriver'
      vacuum_do_not_disturb:
        friendly_name: Do Not Disturb
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.do_not_disturb }}'
        icon_template: >
          {% set val =  states.vacuum.xiaomi_vacuum_cleaner.attributes.do_not_disturb  %}
          {% if val == 'on' %}
            mdi:do-not-disturb
          {% else %}
            mdi:do-not-disturb-off
          {% endif %}
      vacuum_operation:
        value_template: 'Operation'
      vacuum_accessories:
        value_template: 'Maintenance'
        
#################################################################
#                                                               #
#                           vacuum                              # 
#                                                               #
#################################################################

vacuum:
- platform: xiaomi_miio
  host: !secret vacuum_ip
  token: !secret vacuum      
        

#################################################################
#                                                               #
#                           scripts                             # 
#                                                               #
#################################################################
script:
  vacuum_all_home:
        alias: "Vacuum All The House Space"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[23341,19451,32741,30201,1]] ## Tutta la casa ##

  vacuum_bedroom:
        alias: "Vacuum Corridor"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[28489,22014,30139,26214,1]] ## corridoio ##
  vacuum_dining_room:
        alias: "Vacuum Dining Room"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[26253,21948,28503,25948,1]] ## Sala da pranzo #
  vacuum_kitchen:
        alias: "Vacuum Kitchen"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[26115,19477,28315,22027,1]] ## cucina ##
  vacuum_living_room:
        alias: "Vacuum Living Room"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[23327,21890,26077,26040,1]] ## Soggiorno ##
  vacuum_guestroom:
        alias: "Vacuum Dםgs area"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[28624,25960,31574,30260,1]] ## Area cani ##             


#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################

automation:
  - alias: Send alert after daily vacuum to empty the dustbin
    initial_state: 'on'  
    trigger:
    - platform: state
      entity_id: notify.avitelegram 
      to: 'home'
      for:
        minutes: 5
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.daily_vacuum_first_run
        state: 'on'
      - condition: time
        after: '08:30:00'
        before: '23:30:00'
      - condition: template
        value_template: >
          {% if states.automation.send_alert_after_daily_vacuum_to_empty_the_dustbin.last_triggered is not none %}
            {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.send_alert_after_daily_vacuum_to_empty_the_dustbin.attributes.last_triggered) | int > 1800 %} true {% else %} false
            {% endif %}
          {% else %}
          false
          {% endif %}
      - condition: state
        entity_id: input_boolean.disable_dustbin_notification
        state: 'off'
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.living_room_speaker_3
          volume_level: 0.7
      - service: tts.google_say
        entity_id: media_player.living_room_speaker_3
        data_template:
          message: 'Hey, the vacuum dustbin needs to be emptied!'
          cache: false

  - alias: Reset Daily Vacuum First Run state at midnight
    initial_state: 'on'  
    trigger:
      platform: time
      at: '0:00:00'
    action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.daily_vacuum_first_run

  - alias: Start Cleaning Room
    hide_entity: true
    trigger:
    - platform: state
      entity_id: input_select.vacuum_room
      from: 'Select Input'
    action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.vacuum_room", "All The House Space") %}
            script.vacuum_all_home
          {% elif is_state("input_select.vacuum_room", "Kitchen") %}
            script.vacuum_kitchen
          {% elif is_state("input_select.vacuum_room", "Living Room") %}
            script.vacuum_living_room
          {% elif is_state("input_select.vacuum_room", "Dining Room") %}
            script.vacuum_dining_room
          {% elif is_state("input_select.vacuum_room", "Corridor") %}
            script.vacuum_corridor
          {% elif is_state("input_select.vacuum_room", "Dogs area") %}
            script.vacuum_dogs_area           
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.vacuum_room
      data_template:
        option: "Select Input"
        
  - alias: Start Daily Vacuum
    initial_state: 'on'  
    trigger:
    - platform: time_pattern
      minutes: 45
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: device_tracker.avi_note8
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.daily_vacuum_first_run
        state: 'off'
      - condition: time
        after: '11:00:00'
        before: '21:00:00'
      - condition: state
        entity_id: input_boolean.disable_daily_vacuum
        state: 'off'
    action:
    - delay: '00:00:15'
    - service: vacuum.turn_on
      entity_id: vacuum.xiaomi_vacuum_cleaner
    - service: homeassistant.turn_on
      entity_id: input_boolean.daily_vacuum_first_run
