#################################################################
#                                                               #
#                    Packages/Coffee Machine                    #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    light.yeelight_rgb_7c49eb0f97b1:
      friendly_name: תאורה חדר שרתים
      icon: mdi:server      

    light.yeelight_strip_7c49ebadb95c:
      friendly_name: תאורת לד במטבח
      icon: mdi:led-strip
      
      
#################################################################
#                                                               #
#                           Groups                              #
#                                                               #
#################################################################

group:
  yeelight:
    name: Yeelight
    view: no
    entities:
      - light.yeelight_strip_7c49ebadb95c
      - light.yeelight_rgb_7c49eb0f97b1

    
#################################################################
#                                                               #
#                           lights                              #
#                                                               #
#################################################################

light:
  - platform: yeelight
    devices:
      192.xxx.x.xxx:
        name: Computer Room
        transition: 1000
                
  - platform: yeelight
    devices:
      192.xxx.x.xxx:
        name: Kitchen strip Lamp
        transition: 1000     
    
#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################
# automation: