  ## כיבוי שקע תמי4 ##
  - id: Turn_off_Tami_4_in_Night
    alias: 'Turn Off Tami 4 In Night'
    trigger:
    - at: '22:00'
      platform: time
    condition: []
    action:
    - data:
        entity_id: switch.blitzwolf_shp1
      service: switch.turn_off
      
  - id: Turn_on_Tami_4_in_Mornning
    alias: 'Turn On Tami 4 In Mornning'
    trigger:
    - at: '05:45'
      platform: time
    condition: []
    action:
    - data:
        entity_id: switch.blitzwolf_shp1
      service: switch.turn_on

  - id: Auto_off_Tami_4_in_Night
    alias: 'Auto Off Tami 4 In Night'
    trigger:
      - entity_id: switch.service_out_light
        from: 'off'
        platform: state
        to: 'on'
    condition:
      condition: time
      after: '00:00:00'
      before: '05:00:00'
    action:
    - service: timer.start
      entity_id: timer.tami4
      
  - alias: Tami_4_Timerstop
    id: 'Tami 4 Timerstop'
    trigger: 
    - platform: event
      event_type: timer.finished
      event_data: 
        entity_id: timer.tami4
    action:
    - data:
        entity_id: switch.blitzwolf_shp1
      service: switch.turn_off