  alexa:
    filter:
      include_entities: ## להציג ##
        - light.laundry
        - light.parents
        - light.service_balcony  
        - light.balcony
        - light.poop
        - light.prozdor
        - light.stairs
        - light.liran_room
        - switch.tv_lg
        - switch.ac_power
        - script.vacuum_all_home
        - switch.sh20_pow
        - switch.move_channels_down
        - switch.move_channels_up
        - switch.info
        - switch.yes_mute
        - switch.tris_down
        - switch.tris_up
        - sensor.binary_sensors
      include_domains:
        - switch
        - media_player
        - lights
        - sensor
      exclude_entities: ## לא להציג ##
        - media_player.living_room_tv
        - group.version
        - group.all_devices
        - group.weather_sensor
        - group.lighting
        - group.homeassistent
        - group.miscellaneous
        - media_player.mibox3
        - media_player.unnamed_device
        - switch.ac_fan_speed
        - switch.lg_volume_up
        - switch.ac_timer
        - switch.ac_temp_down
        - switch.ac_mode
        - switch.lg_volume_down
        - switch.ac_temp_up
        - media_player.safari
        - sensor.hdd_sdi_temp
        - sensor.hdd_sde_temp
        - sensor.hdd_sdc_temp
        - sensor.hdd_sdf_temp
        - sensor.hdd_sdg_temp
        - sensor.hdd_sdd_temp
        - sensor.hdd_sdh_temp
        - sensor.cpu_temp
        - sensor.hdd_sdb_temp
        - media_player.safari_4
        - media_player.safari_3
        - media_player.whizz
        - media_player.whizz_2
        - media_player.kodi
 
    entity_config:
      light.laundry:
        name: Laundry room
        description: להדליק את האור בחדר כביסה

      light.parents:
        name: Parents
        description: להדליק את התאורה בחדר הורים  

      light.service_balcony:
        name: service balcony  
        description: להדליק את האור במרפסת שירות

      light.balcony:
        name: balcony
        description: להדליק את התאורה במרפסת הראשית

      light.poop: 
        name: Poop
        description: להדליק את האור בשירותי אורחים   

      light.stairs:
        name: stairs
        description: להדליק את האור במדרגות

      light.liran_room: 
        name: liran 
        description:  להדליק את האור בחדר של לירן

      light.prozdor:
        name: prozdor
        description: תאורה בפרוזדור

      switch.tv_lg:
        name: tv               
        description: להדליק את הטלוויזיה בסלון

      switch.ac_power:
        name: mazgan
        description: להדליק את המזגן    

      script.vacuum_all_home:
        name: robot
        description: לשאוב את כל הבית

      switch.sh20_pow:
        name: home camera
        description: כיבוי מצלמת אבטחה בבית

      switch.move_channels_down:
        name: move channel down
        description: העברת ערוץ אחורה

      switch.move_channels_up:
        name: move chammel up
        description: העברת ערוץ קדימה   
    
      switch.info:
        name: info
        description: מידע על התוכנית המשודרת

      switch.yes_mute:
        name: mute
        description: השתקה
      
      switch.tris_down:
        name: tris lemata
        description: הורדת התריס למטה
      
      switch.tris_up:
        name: tris lemala
        description: הרמת התריס למעלה
        

      sensor.second_floor_temperature:
        name: temperature second floor
        description: טמפ׳ קומה שניה
      
      sensor.temperature_158d00022ece24:
        name: Temp in the living Room
        description: טמפ בסלון
      
      switch.blitzwolf_shp1:
        name: water
        description: כיבוי חשמל לתמי 4
      
      switch.washing_machine:
        name: washing machine
        description: כיבוי או הדלקה מכונת כביסה