#################################################################
#                                                               #
#                          Feed The Dog                         #
#                                                               #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################
homeassistant:
  # customize:





#################################################################
#                                                               #
#                           Groups                              #
#                                                               #
#################################################################
group:


#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################
automation:

    #########################  FEED THE DOG - MORNING   ########################## 
  - alias: "Feed The Dog Morning"
    initial_state: 'on'
    trigger:
      platform: time
      at: '09:00:00'
    action:
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_34ce008d4e2e
        brightness: 254
        color_name: blue

    - service: notify.avitelegram
      data:
        title: "כלבים"
        message: האם סקאי וגוצי אכלו ארוחת בוקר?   

    - service: notify.iphone_nurit
      data:
        title: "כלבים"
        message: האם סקאי וגוצי אכלו ארוחת? 
        data:
          push:
            sound: "US-EN-Morgan-Freeman-Good-Morning.wav"
            badge: 0
            category: 'feedthedog' #the indentefier
          attachment: 
            url: https://1.bp.blogspot.com/-XKiTW7HSllI/WQRkJFhY2XI/AAAAAAAHRio/yIjWWH8-VZsPBrWkQxCQjGYPz_6RTsiagCLcB/s1600/AW419408_06.gif        


    - delay: 0:00:03
    - service: light.turn_off
      entity_id: light.gateway_light_34ce008d4e2e

    - delay: 0:00:01
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_34ce008d4e2e
        brightness: 254
        color_name: blue

    - delay: 0:00:15
    - service: light.turn_off
      entity_id: light.gateway_light_34ce008d4e2e
      
      
    #########################  FEED THE DOG - EVENING   ##########################
  - alias: "Feed The Dog Evening"
    initial_state: 'on'
    trigger:
      platform: time
      at: '19:00:00'
    action:
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_34ce008d4e2e
        brightness: 254
        color_name: blue

    - delay: 0:00:03
    - service: light.turn_off
      entity_id: light.gateway_light_34ce008d4e2e

    - delay: 0:00:01
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_34ce008d4e2e
        brightness: 254
        color_name: blue

    - delay: 0:00:15
    - service: light.turn_off
      entity_id: light.gateway_light_34ce008d4e2e

    - service: notify.avitelegram
      data:
        title: "כלבים"
        message: האם סקאי וגוצי אכלו ארוחת ערב?
        
  ## לא למחוק לבדוק למה זה לא עובד מבחינת הזמנים #
  # #########################  FReset Feed The Dog Notifications   ##########################
  # - alias: "Reset Feed The Dog Notifications"
  #   initial_state: 'on'
  #   trigger:
  #     platform: time
  #     at: '02:00:00'
  #   action:
  #     - service: automation.turn_on
  #       entity_id: automation.dog_has_been_fed__evening
  #     - service: automation.turn_on
  #       entity_id: automation.dog_has_been_fed__morning
  #     - service: automation.turn_on
  #       entity_id: automation.feed_the_dog_evening
  #     - service: automation.turn_on
  #       entity_id: automation.feed_the_dog_morning        